Bereket
bjornarhagen/edu-hio-wordpress pull request #16
Opened 2019-04-26 17:38 UTC by bereketgadhanom

2019-04-27 13:12 UTC, bjornarhagen commented
Merge master inn i din egen branch først

2019-04-27 15:53 UTC, bjornarhagen requested changes
Mange filer med merge confilcts som ikke har blitt fikset ordentlig.

Se alle filer som har
Kode som: ` <<<<<<< HEAD` og `>>>>>>> master`

Dette skal ikke være med...
Dette kommer når du får en merge conflict og bare trykker "Resolve" uten å gjøre noe. Du kan ikke gjøre sånn, du må faktisk gå gjennom filen og kun ta med relevant kode.

Ser også at det er endringer i filer som du ikke har hatt noe med å gjøre. Som blant annet inc/custom-header-fields.php og header.php.

2019-04-29 00:42 UTC, bjornarhagen requested changes

2019-04-29 00:42 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/header.php
> +	<div id="content" class="site-content">
Dette er gammel kode fra meg, hvorfor blir dette sendt inn?

2019-04-29 00:42 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/functions.php
> +add_filter( 'the_content_more_link', 'modify_read_more_link' );
Duplikat kode

2019-04-29 00:42 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/inc/custom-header-fields.php
> +
Gammel kode fra meg...

2019-04-29 00:42 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/inc/custom-header.php
> +
Gammel kode som har blitt slettet...

2019-04-29 00:42 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/inc/custom-header.php
> +		// If we get this far, we have custom styles. Let's do this.
Gammel kode

2019-04-29 00:42 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/sass/elements/_elements.scss
> +button,
Button styling skal her: `/sass/forms/_buttons.scss`

2019-04-29 08:00 UTC, bereketgadhanom commented on wp-content/themes/havnehotellet-i-halden/sass/elements/_elements.scss
> +button,
Button styling flyttet til /sass/forms/_buttons.scss og input styling flyttet til /sass/forms/_fields.scss

2019-04-29 15:44 UTC, bjornarhagen requested changes
node_modules skal ikke inn i git.
Legg mappen i gitignore

2019-04-30 09:26 UTC, bjornarhagen requested changes
node_modules ligger forsatt i denne pull requesten. Slett mappen. Skal ikke inn i git

2019-04-30 12:06 UTC, bjornarhagen requested changes

2019-04-30 12:06 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/sass/elements/_elements.scss
> +button,
Ikke fikset enda

2019-04-30 12:06 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/sass/site/primary/_archive.scss
> +.site-main {
Hva skjer i denne filen?
Innholdet kommer 2 ganger

2019-04-30 12:06 UTC, bjornarhagen commented on wp-content/themes/havnehotellet-i-halden/sass/variables-site/_colors.scss
> +$dark: #000 ;
Er dette endringer du har gjort?
Fjern hvis du ikke har gjort dem...

2019-05-02 10:49 UTC, bjornarhagen approved these changes

2019-05-02 10:49 UTC, merged